### ISSUE TITLE
ServoMotor.yaml

### ISSUE THREAD

**Issue by n-ando** [n-ando/n-ando.github.io#10]
```yaml
moduleName: TDA040-P1630FA0-01BA0
description: TD series servo motor
manufactures:	Tsino-Dynatron Electrical Technology (Beijing) Co., Ltd.	
examples:	
idnType:
  # uuid.uuid5(uuid.NAMESPACE_DNS, "tsino-dynatron.com")
  # UUID(16)-PID(4)-Rev(4)-SerialNo(4)-Category(3)-IID(1)
  - moduleID: 64bb49ed-bb76-5ae0-9b14-9e22b6bfd43b-00000001-00000001-00000001-000001-0
  - iID: -
  - informationModelVersion: 1.0.0
  - hwAspects: -
  - swAspects: -	
ModuleProperties:
properties:
    - name: rated_power
      description: Rated Power
      type: float
      unit: W
      value: 50
    - name: rated_current
      description: Rated Current
      type: float
      unit: A rms
      value: 1.25
    - name: rated_torque
      description: Rated Torque
      type: float
      unit: A rms
      value: 1.25
    - name: max_torque
      description: Max Torque
      type: float
      unit: Nm
      value: 0.477
    - name: rated_speed
      description: Rated Speed
      type: float
      unit: rpm
      value: 3000
    - name: max_speed
      description: Max Speed
      type: float
      unit: rpm
      value: 6000
    - name: back_emf
      description: Back Emf
      type: float
      unit: V/1000rpm
      value: 8.6
    - name: torque_constant
      description: Torque Constant
      type: float
      unit: Nm/A
      value: 0.13
    - name: line_resistance
      description: Line Resistance
      type: float
      unit: ohm
      value: 8.9
    - name: electrical_time_constant
      description: Electrical Time Constant
      type: float 
      unit: ms
      value: 1.0
    - name: roter_inrtia
      description: Rotor Inertial
      type: float
      unit: kgm^2
      value: 0.034*10^-4
    - name: mass
      description: Mass
      type: float
      unit: kg
      value: 0.4
    - name: body_length
      description: Body Length
      type: float
      unit: mm
      value: 59.3
    - name: number_of_poles
      description: Number of Poles
      type: int
      unit: 
      value: 10
    - name: insulation_class
      description: Insukation Class
      type: float
      unit: degree Celsius
      value: 155
    - name: ingress_protection
      description: Ingress Protection
      type: string
      unit: 
      value: IP65
    - name: operation_temperature_min
      description: Operation Temperature Min
      type: float
      unit: degree Celsius
      value: 0.0
    - name: operation_temperature_max
      description: Operation Temperature Max
      type: float
      unit: degree Celsius
      value: 40.0
    - name: operation_humidity_max
      description: Operation Humidity Max
      type: float
      unit: %
      value: 90.0
IOVariables:
  - variable:
    ioType: IN
    description: Torque input
    name: torque
    type: float
    unit: Nm
  - variable:
    ioType: OUT (example)
    description: temperature
    name: temp
    type: float
    unit: Celsius
Status: <- unneccesarry for the motor? is this a specification or current value?
  - healthCond:
  - executionStatus:
  - errorType:
Services:
Infrastructure:
Safety/security:
Modelling:
ExecutableForm:



```
